#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bash /home/laser/.config/polybar/launch.sh
picom &
xsetroot -cursor_name left_ptr
feh --bg-scale /home/laser/Bilder/Wallpapers/new/art3_auto_x2.jpg

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

